type: object
requires: ["homeserver", "messenger"]
properties:
  homeserver:
    type: object
    properties:
      url:
        type: string
      domain:
        type: string
      room_id:
        type: string
    additionalProperties: false
    required: ["url", "domain", "room_id"]
  messenger:
    type: object
    properties:
      secret:
        type: string
      token:
        type: string
      verify:
        type: string
    additionalProperties: false
    required: ["secret", "token", "verify"]